---
- name: fetch latest version using uri module
  include: latest-uri.yml
  when: ansible_version.full is version('2.0.2', '>=')

- name: fetch latest version using curl
  include: latest-curl.yml
  when: minecraft_version_latest is not defined
